shiro:
    filterChainDefinitions: |
        /logout = logout
        /login = anon
        /login_in = anon
        /* = authc
        /** = authc
   #/logout = logout表示登出 | 表示 换行符\n
   #/admin/** = authc, roles[admin]
   #/docs/** = authc, perms[document:read]
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
          prefix: /
          suffix: .html
          #static-path-pattern: classpath:/static/
          #默认默认值为 classpath:/META-INF/resources/,
          #classpath:/resources/,
          #classpath:/static/,
          #classpath:/public/
          #spring.resources.static-locations=classpath:/other/
          #使用 spring.mvc.static-path-pattern 可以重新定义pattern，
          #如修改为 /myres/** ，则访问static 等目录下的fengjing.jpg文件应该为
          #http://localhost:8080/myres/fengjing.jpg ，修改之前为 http://localhost:8080/fengjing.jpg
          #使用 spring.resources.static-locations 可以重新定义 pattern 所指向的路径，支持 classpath: 和 file: